# Generated by Django 2.2.12 on 2021-09-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0002_auto_20210913_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefon',
            old_name='user',
            new_name='owner',
        ),
    ]
